# Site settings
title: Cross Country and Track Club at NC State
email: ncsu.cctrack.club@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    The site of the NC State Club Cross Country and Track team! Visit our page to
    learn about practices, meets, social events, and our team.
baseurl: ""
url: "http://ncsuclubrunning.com/"
markdown: kramdown



facebook_page: "https://www.facebook.com/groups/31185019441/"
practice_location: "https://www.google.com/maps/place/35%C2%B046'56.0%22N+78%C2%B040'19.8%22W/@35.7822222,-78.6721667,18z/data=!3m1!4b1!4m2!3m1!1s0x0:0x0"
year: 2017



page_data:
  - title: "Home"
    id: "home"
    url: ""

  - title: "Practice"
    id: "practice"
    url: "practice"

  - title: "Training"
    id: "training"
    url: "training"
 
  - title: "Schedule"
    id: "schedule"
    url: "schedule"

  - title: "Race Results"
    id: "race-results"
    url: "race-results"

  - title: "Store"
    id: "store"
    url: "store"

  - title: "Club Officers"
    id: "club-officers"
    url: "club-officers"

  - title: "FAQ"
    id: "faq"
    url: "faq"

  - title: "Contact Us"
    id: "contact-us"
    url: "contact-us"
